#!/bin/bash
# icons depend on nerdfonts being installed
hostname="${HOSTNAME:-${hostname:-$(hostname)}}"

network() {

    # Check if able to connect to internet
    ping_results=$(ping -c 3 google.com | grep '64 bytes' | wc -l)

    if [ $ping_results -lt 1 ]; then
        echo "睊"
        exit
    fi

    # Check type of connection
    wire="$(ip a | grep 'eth0\|enp' | grep inet | wc -l)"  # fix this, is bullshit
    wifi="$(ip a | grep 'wlan\|wlp' | grep 'state UP' | wc -l)"

    if [ $wire = 1 ]; then 
        echo ""
    elif [ $wifi = 1 ]; then
       # echo "  $(hostname -I | awk '{print $1}')"
        echo "^c#00bbf9^" 
    else 
        echo "?睊?"
    fi
}

vpn() {
    state="$(ip a | grep 'tun0\|vpn' | grep 'state UP' | wc -l)"
    
    if [ $state = 1 ]; then
        echo "ﱾ"
    else
        echo " "
    fi
}

echo "$(network) $(vpn)" 
