#!/bin/bash

VOLONOFF="$(amixer -D pulse get Master | grep Left: | sed 's/[][]//g' | awk '{print $6}')"
VOL="$(amixer -D pulse get Master | grep Left: | sed 's/[][]//g' | awk '{print $5}')"

VOLICON=""
MUTEICON="婢"


if [ "$VOLONOFF" = "on" ]; then
	echo "^c#00f5d4^$VOLICON $VOL"
else
	echo "^c#00f5d4^$MUTEICON"
fi
